### ISSUE TITLE
Throw Exception with Jrockit 1.6 "Trying to get a virtual dispatch offset ..."

### ISSUE THREAD

**Issue by erolg** [cjmx/cjmx#18]
`$ /Oracle/Middleware/jrockit_160_22_D1.1.1-3/bin/java -cp /Oracle/Middleware/jrockit_160_22_D1.1.1-3/lib/tools.jar:/cjmx-master/cjmx_2.10-2.3.0-app.jar cjmx.Main`

[ERROR][class  ] Trying to get a virtual dispatch offset for interface scala/collection/immutable/StringLike
Exception in thread "Main Thread" java.lang.ExceptionInInitializerError
    at cjmx.App$.run(App.scala:33)
    at cjmx.Main$.main(Main.scala:7)
    at cjmx.Main.main(Main.scala)
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Matcher.java:1140)
    at java.util.regex.Matcher.reset(Matcher.java:291)
    at java.util.regex.Matcher.<init>(Matcher.java:211)
    at java.util.regex.Pattern.matcher(Pattern.java:888)
    at java.util.Formatter.parse(Formatter.java:2458)
    at java.util.Formatter.format(Formatter.java:2414)
    at java.util.Formatter.format(Formatter.java:2367)
    at java.lang.String.format(String.java:2769)
    at scala.collection.immutable.StringLike$class.format(StringLike.scala:266)
    at scala.collection.immutable.StringOps.format(StringOps.scala:31)
    at cjmx.cli.REPL$.<init>(REPL.scala:66)
    at cjmx.cli.REPL$.<clinit>(REPL.scala)
    ... 3 more

**Comment by mpilquist** [comment]
Hm, the line it is crashing on is:
```scala
  private val newline = "%n".format()
```
Could you try executing `"%n".format()` on JRockit and seeing if it compiles or throws the exception above?
